/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-05-16 01:15:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class HomeScreen_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Online Vehicle Service & Fuel Station Management</title>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/*header*/\r\n");
      out.write(".header {\r\n");
      out.write("  background-color: #273444;\r\n");
      out.write("  color: white;\r\n");
      out.write("  padding: 20px;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  height:80px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logo {\r\n");
      out.write("  flex: 1;\r\n");
      out.write("  margin-top: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logo img {\r\n");
      out.write("  width: 100px; /* Set the width of the logo */\r\n");
      out.write("  height: 80px; /* Maintain aspect ratio */\r\n");
      out.write("  margin-left:30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".title {\r\n");
      out.write("  flex: 3;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".move-text{\r\n");
      out.write("    margin-top: 5px; \r\n");
      out.write("    margin-right: 520px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".moved-text{\r\n");
      out.write("  margin-top: 10px; \r\n");
      out.write("  margin-right: 250px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar {\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("  background-color: #333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar a {\r\n");
      out.write("  float: left;\r\n");
      out.write("  display: block;\r\n");
      out.write("  color: white;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  padding: 14px 20px;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar a:hover {\r\n");
      out.write("  background-color: #ddd;\r\n");
      out.write("  color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-container {\r\n");
      out.write("  float: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-container input[type=text] {\r\n");
      out.write("  padding: 6px;\r\n");
      out.write("  margin-top: 8px;\r\n");
      out.write("  margin-bottom: 8px;\r\n");
      out.write("  margin-right: 16px;\r\n");
      out.write("  border: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-container button {\r\n");
      out.write("  padding: 6px 10px;\r\n");
      out.write("  margin-top: -10px;\r\n");
      out.write("  margin-bottom: -4px;\r\n");
      out.write("  margin-right: 16px;\r\n");
      out.write("  background: #ddd;\r\n");
      out.write("  font-size: 14px;\r\n");
      out.write("  border: none;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media screen and (max-width: 600px) {\r\n");
      out.write("  .navbar a, .search-container {\r\n");
      out.write("    float: none;\r\n");
      out.write("    display: block;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  .search-container {\r\n");
      out.write("    margin-top: 8px;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main-content {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  justify-content: space-between;\r\n");
      out.write("  align-items: flex-start;\r\n");
      out.write("  margin-top: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".slider-container {\r\n");
      out.write("  width: 60%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".slider {\r\n");
      out.write("  position: relative;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 400px;\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("  border: 2px solid black;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".slide {\r\n");
      out.write("  display: none;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".active-slide {\r\n");
      out.write("  display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-container {\r\n");
      out.write("  width: 38%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card {\r\n");
      out.write("  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);\r\n");
      out.write("  transition: 0.3s;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  margin: 10px 0; \r\n");
      out.write("  padding: 60px;\r\n");
      out.write("  background-color: LightSlateGray;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card:hover {\r\n");
      out.write("  box-shadow: 0 8px 16px 0 rgba(0, 0, 0, 0.2);\r\n");
      out.write("  color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card h3 {\r\n");
      out.write("  margin-top: 10px;\r\n");
      out.write("  font-size: 22px; /* Adjust the font size */\r\n");
      out.write("  color: HoneyDew; /* Adjust the text color */\r\n");
      out.write("  font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*footer*/\r\n");
      out.write(".footer {\r\n");
      out.write("  background-color: #1a1a2e;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  padding: 20px 0;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  margin-top: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer h5 {\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  font-size: 18px;\r\n");
      out.write("  font-weight: 600;\r\n");
      out.write("  margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer ul {\r\n");
      out.write("  list-style: none;\r\n");
      out.write("  padding-left: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer ul li {\r\n");
      out.write("  margin-bottom: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer a {\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer a:hover {\r\n");
      out.write("  color: #ccc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer p {\r\n");
      out.write("  margin-bottom: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer .py-3 {\r\n");
      out.write("  padding-top: 0.5rem;\r\n");
      out.write("  padding-bottom: 0.5rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer .text-center {\r\n");
      out.write("  text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer .copy {\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer .contact {\r\n");
      out.write("  margin-left: 200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer .about {\r\n");
      out.write("  margin-left: 1000px;\r\n");
      out.write("  margin-top: -130px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"header\">\r\n");
      out.write("  <div class=\"logo\">\r\n");
      out.write("    <img src=\"Image/2.png\" alt=\"ServicePulse Logo\">\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"title\">\r\n");
      out.write("    <h1 class=\"move-text\">ServicePulse</h1>\r\n");
      out.write("    <h2 class=\"moved-text\">Welcome To ServicePulse! Online Vehicle and Fuel Management System</h2>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"navbar\">\r\n");
      out.write("  <a href=\"HomeScreen.jsp\">Home</a>\r\n");
      out.write("  <a href=\"AboutUs.jsp\">About Us</a>\r\n");
      out.write("  <a href=\"branches.jsp\">Branches</a>\r\n");
      out.write("  <a href=\"Package.jsp\">Packages</a>\r\n");
      out.write("  <div class=\"search-container\">\r\n");
      out.write("    <a href=\"login.jsp\">\r\n");
      out.write("  <button type=\"submit\">Admin login</button>\r\n");
      out.write("</a>\r\n");
      out.write("   \r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("  \r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<div class=\"main-content\">\r\n");
      out.write("  <div class=\"slider-container\">\r\n");
      out.write("    <div class=\"slider\">\r\n");
      out.write("      <img class=\"slide active-slide\" src=\"Image/home22.jpg\" alt=\"Image 1\">\r\n");
      out.write("      <img class=\"slide\" src=\"Image/home5.jpg\" alt=\"Image 2\">\r\n");
      out.write("      <img class=\"slide\" src=\"Image/home44.jpg\" alt=\"Image 3\">\r\n");
      out.write("      <img class=\"slide\" src=\"Image/home3.jpg\" alt=\"Image 4\">\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"card-container\">\r\n");
      out.write("    <div class=\"card\" onclick=\"window.location.href='login.jsp'\">\r\n");
      out.write("      <h3>Vehicle Services</h3>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"card\" onclick=\"window.location.href='FuelDp.jsp'\">\r\n");
      out.write("      <h3>Fuel Dispense</h3>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<footer class=\"footer\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"contact\"> \r\n");
      out.write("            <h5>Contact Us</h5>\r\n");
      out.write("            <ul class=\"list-unstyled\">\r\n");
      out.write("                <li><a href=\"#\">Email: info@servicepulse.com</a></li>\r\n");
      out.write("                <li><a href=\"#\">Phone: 011-2222211</a></li>\r\n");
      out.write("                <li><a href=\"#\">Address: No.34, Flower Road, Colombo 5</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"about\"> \r\n");
      out.write("            <h5>About Us</h5>\r\n");
      out.write("            <ul class=\"list-unstyled\">\r\n");
      out.write("                <li><a href=\"#\">Company Overview</a></li>\r\n");
      out.write("                <li><a href=\"#\">Our Team</a></li>\r\n");
      out.write("                <li><a href=\"#\">Privacy Policy</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"copy\">\r\n");
      out.write("        <p>&copy; 2023 ServicePulse. All rights reserved.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("// JavaScript for image slider\r\n");
      out.write("let currentSlide = 0;\r\n");
      out.write("const slides = document.querySelectorAll('.slide');\r\n");
      out.write("\r\n");
      out.write("function showSlide(index) {\r\n");
      out.write("  slides[currentSlide].classList.remove('active-slide');\r\n");
      out.write("  currentSlide = (index + slides.length) % slides.length;\r\n");
      out.write("  slides[currentSlide].classList.add('active-slide');\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function nextSlide() {\r\n");
      out.write("  showSlide(currentSlide + 1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function prevSlide() {\r\n");
      out.write("  showSlide(currentSlide - 1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("setInterval(nextSlide, 3000); // Change image every 3 seconds\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
