/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-05-16 01:32:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert Customer</title>\r\n");
      out.write("<style>\r\n");
      out.write("    /* CSS styles for form elements */\r\n");
      out.write("    body {\r\n");
      out.write("        background-color: #D6EAF8;\r\n");
      out.write("        font-family: Arial, sans-serif;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .form-container {\r\n");
      out.write("       max-width: 350px;\r\n");
      out.write("        margin: 20px auto;\r\n");
      out.write("        background-color: #D5F5E3;\r\n");
      out.write("        padding: 60px;\r\n");
      out.write("        border-radius: 20px;\r\n");
      out.write("        box-shadow: 0px 0px 10px 0px rgba(0,0,0,0.1);\r\n");
      out.write("       \r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    input[type=\"text\"] {\r\n");
      out.write("        width: calc(100% - 10px);\r\n");
      out.write("        padding: 10px;\r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("        border-radius: 20px;\r\n");
      out.write("        border: 1px solid #ccc;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    input[type=\"submit\"] {\r\n");
      out.write("        width: calc(100% - 10px);\r\n");
      out.write("        padding: 10px;\r\n");
      out.write("        background-color: #007bff;\r\n");
      out.write("        color: #fff;\r\n");
      out.write("        border: none;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    input[type=\"submit\"]:hover {\r\n");
      out.write("        background-color: #0056b3;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .h1 {\r\n");
      out.write("        color: #007bff;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("	.header {\r\n");
      out.write("  background-color: #273444;\r\n");
      out.write("  color: white;\r\n");
      out.write("  padding: 25px;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  height:30px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write(".logo {\r\n");
      out.write("  flex: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".title {\r\n");
      out.write("  flex: 3;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".move-text{\r\n");
      out.write("   \r\n");
      out.write("    margin-top: 5px; \r\n");
      out.write("    margin-right: 520px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".moved-text{\r\n");
      out.write("  margin-top: 10px; \r\n");
      out.write("    margin-right: 250px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".navbar {\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("  background-color: #333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar a {\r\n");
      out.write("  float: left;\r\n");
      out.write("  display: block;\r\n");
      out.write("  color: white;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  padding: 14px 20px;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar a:hover {\r\n");
      out.write("  background-color: #ddd;\r\n");
      out.write("  color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-container {\r\n");
      out.write("  float: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-container input[type=text] {\r\n");
      out.write("  padding: 6px;\r\n");
      out.write("  margin-top: 8px;\r\n");
      out.write("  margin-bottom: 8px;\r\n");
      out.write("  margin-right: 16px;\r\n");
      out.write("  border: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-container button {\r\n");
      out.write("  padding: 5px 5px;\r\n");
      out.write("  margin-top: 4px;\r\n");
      out.write("  margin-bottom: 10px;\r\n");
      out.write("  margin-right: 2px;\r\n");
      out.write("  background: #ddd;\r\n");
      out.write("  font-size: 15px;\r\n");
      out.write("  border: none;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media screen and (max-width: 600px) {\r\n");
      out.write("  .navbar a, .search-container {\r\n");
      out.write("    float: none;\r\n");
      out.write("    display: block;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  .search-container {\r\n");
      out.write("    margin-top: 8px;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer {\r\n");
      out.write("    background-color: #1a1a2e;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    padding: px 0; /* Decrease padding */\r\n");
      out.write("    bottom: 5px; /* Place at the bottom */\r\n");
      out.write("    left: 0;\r\n");
      out.write("    width: auto;\r\n");
      out.write("    margin-top: 70px;\r\n");
      out.write("    height: 150px;\r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".footer h5 {\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    font-size: 18px; /* Decrease font size */\r\n");
      out.write("    font-weight: 600;\r\n");
      out.write("    margin-bottom: 10px; /* Decrease margin */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer ul {\r\n");
      out.write("    list-style: none;\r\n");
      out.write("    padding-left: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer ul li {\r\n");
      out.write("    margin-bottom: 5px; /* Decrease margin */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer a {\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer a:hover {\r\n");
      out.write("    color: #ccc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer p {\r\n");
      out.write("    margin-bottom: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer .py-3 {\r\n");
      out.write("    padding-top: 0.5rem; /* Decrease padding */\r\n");
      out.write("    padding-bottom: 0.5rem; /* Decrease padding */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer .text-center {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer .copy {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer .contact{\r\n");
      out.write("  margin-left:200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".footer .about{\r\n");
      out.write("  margin-left:1000px;\r\n");
      out.write("  margin-top:-130px;\r\n");
      out.write("}\r\n");
      out.write(".main_text {\r\n");
      out.write("    max-width: 20%;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main_text h1 {\r\n");
      out.write("    font-size: 3rem;\r\n");
      out.write("    margin-bottom: 30px;\r\n");
      out.write("    font-family: \"Times New Roman\", Times, serif;\r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	  \r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"header\">\r\n");
      out.write(" 			\r\n");
      out.write("  			<div class=\"title\">\r\n");
      out.write("    		\r\n");
      out.write("    			<h3 class=\"moved-text\">Welcome To ServicePulse! Online Vehicle and Fuel Management System</h3>\r\n");
      out.write(" 			 </div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"navbar\">\r\n");
      out.write("  		<a href=\"#home\">Home</a>\r\n");
      out.write("  		<a href=\"#about\">About Us</a>\r\n");
      out.write("  		<a href=\"#branches\">Branches</a>\r\n");
      out.write("  		<a href=\"#packages\">Packages</a>\r\n");
      out.write("  	\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write(" 			<div class=\"main_text\">\r\n");
      out.write("                <h2>CUSTOMER DETAILS</h2>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"form-container\">\r\n");
      out.write("		\r\n");
      out.write("           <form id=\"customerForm\" action=\"");
      out.print( request.getContextPath());
      out.write("/AddCustomerServlet\" method=\"post\">\r\n");
      out.write("       			 First Name <input type=\"text\" name=\"firstname\" id=\"firstname\"><br>\r\n");
      out.write("        		 Last Name <input type=\"text\" name=\"lastname\" id=\"lastname\"><br>\r\n");
      out.write("        		 Address <input type=\"text\" name=\"address\" id=\"address\"><br>\r\n");
      out.write("        		 Mobile Number <input type=\"text\" name=\"mobileno\" id=\"mobileno\"><br>\r\n");
      out.write("        <input type=\"submit\" value=\"Add Customer\" onclick=\"return validateForm()\"><br>\r\n");
      out.write("    </form>\r\n");
      out.write(" </div>\r\n");
      out.write(" \r\n");
      out.write(" <footer class=\"footer\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        \r\n");
      out.write("            <div class=\"contact\"> \r\n");
      out.write("                <h5>Contact Us</h5>\r\n");
      out.write("                <ul class=\"list-unstyled\">\r\n");
      out.write("                    <li><a href=\"#\">Email: info@servicepulse.com</a></li>\r\n");
      out.write("                    <li><a href=\"#\">Phone: 011-2222211</a></li>\r\n");
      out.write("                    <li><a href=\"#\">Address: No.34, Flower Road, Colombo 5</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"about\"> \r\n");
      out.write("                <h5>About Us</h5>\r\n");
      out.write("                <ul class=\"list-unstyled\">\r\n");
      out.write("                    <li><a href=\"#\">Company Overview</a></li>\r\n");
      out.write("                    <li><a href=\"#\">Our Team</a></li>\r\n");
      out.write("                    <li><a href=\"#\">Privacy Policy</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("  \r\n");
      out.write("    <div class=\"copy\">\r\n");
      out.write("        <p>&copy; 2023 ServicePulse. All rights reserved.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("	<script>\r\n");
      out.write("    function validateForm() {\r\n");
      out.write("        var firstName = document.getElementById(\"firstname\").value;\r\n");
      out.write("        var lastName = document.getElementById(\"lastname\").value;\r\n");
      out.write("        var address = document.getElementById(\"address\").value;\r\n");
      out.write("        var mobileNo = document.getElementById(\"mobileno\").value;\r\n");
      out.write("\r\n");
      out.write("        if (firstName == \"\" || lastName == \"\" || address == \"\" || mobileNo == \"\") {\r\n");
      out.write("            alert(\"All fields must be filled out\");\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // You can add more specific validation rules here, such as checking if mobile number is valid.\r\n");
      out.write("\r\n");
      out.write("        return true;\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    // Function to enforce numeric input and limit to 10 digits\r\n");
      out.write("    function restrictMobileInput(event) {\r\n");
      out.write("        var input = event.target.value;\r\n");
      out.write("        \r\n");
      out.write("        // Remove any non-numeric characters\r\n");
      out.write("        var numericInput = input.replace(/\\D/g, '');\r\n");
      out.write("        \r\n");
      out.write("        // Limit input to 10 digits\r\n");
      out.write("        var trimmedInput = numericInput.substring(0, 10);\r\n");
      out.write("        \r\n");
      out.write("        // Update the input field value\r\n");
      out.write("        event.target.value = trimmedInput;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    // Get the mobile number input field\r\n");
      out.write("    var mobileInput = document.getElementById(\"mobileno\");\r\n");
      out.write("\r\n");
      out.write("    // Attach event listener to the \"input\" event for the mobile number input field\r\n");
      out.write("    mobileInput.addEventListener(\"input\", restrictMobileInput);\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
